[tool.poetry]
name = "sshnpdpy"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
bcrypt = "^4.0.1"
cffi = "^1.15.1"
cryptography = "^41.0.3"
paramiko = "3.3.1"
pycparser = "^2.21"
PyNaCl = "^1.5.0"
setuptools = "^68.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
