[tool.poetry]
name = "sshnpdpy"
version = "0.3.0"
description = ""
authors = ["Xavier Lin <@Xlin123>"]
readme = "README.md"

[tool.poetry.scripts]
sshnpdpy = 'sshnpdpy:main'

[tool.poetry.dependencies]
python = "^3.10"
bcrypt = "^4.0.1"
cffi = "^1.15.1"
cryptography = "^41.0.3"
paramiko = "3.3.1"
pycparser = "^2.21"
PyNaCl = "^1.5.0"
setuptools = "^69.0.0"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
