version: "3.0"

volumes:
  keys:
    driver: local
services:
  activate:
    build:
      context: ../../
      dockerfile: ./templates/docker/Dockerfile.activate
    volumes:
      - keys:/atsign/.atsign/keys
    command: -a "@sshnpdatsign" -c "from-my.atsign.com-under-advanced-settings"
  sshnpd:
    image: atsigncompany/sshnpd:latest
    volumes:
      - keys:/atsign/.atsign/keys
    command: -a "@sshnpdatsign" -m "@sshnpatsign" -d "devicename" -s -u -v
    depends_on:
      - activate
