name: sshnoports

packages:
  - packages/noports_core
  - packages/sshnoports
  - packages/sshnp_gui

command:
  bootstrap:
    hooks:
      post: dart run melos exec --scope="noports_core" --scope="sshnoports" -- "dart run build_runner build"
