name: sshnoports
publish_to: none

version: 4.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  noports_core: 5.1.0
  at_onboarding_cli: 1.4.1
  args: 2.4.2
  socket_connector: ^2.0.0

dependency_overrides:
  # Pin the dependencies of noports_core
  archive: 3.3.9
  args: 2.4.2
  at_client: 3.0.71
  at_lookup: 3.0.41
  at_utils: 3.0.15
  asn1lib: 1.4.1
  encrypt: 5.0.1
  crypton: 2.1.0
  dartssh2: 2.8.2
  logging: 1.2.0
  meta: 1.9.1
  ssh_key: 0.8.0
  uuid: 3.0.7
  version: 3.0.2
  socket_connector:
    git:
      url: https://github.com/gkc/socket_connector.git
      ref: socket-authenticator-option

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
  mocktail: ^1.0.2
  build_runner: ^2.4.8
  build_version: ^2.1.1
