name: sshnoports
publish_to: none

version: 5.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  noports_core:
    path: "../noports_core"
  at_onboarding_cli: 1.4.3
  at_cli_commons: ^1.0.4
  args: 2.4.2
  socket_connector: ^2.1.0
  dartssh2: 2.8.2
  at_utils: 3.0.16

dependency_overrides:
  socket_connector:
    git:
      ref: gkc/enhance-server-to-socket
      url: https://github.com/atsign-foundation/socket_connector
  args:
    git:
      ref: gkc/show-aliases-in-usage
      url: https://github.com/gkc/args

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  mocktail: ^1.0.3
  build_runner: ^2.4.8
  build_version: ^2.1.1
