name: sshnoports
publish_to: none

version: 5.3.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  noports_core:
    path: "../noports_core"
  at_onboarding_cli: 1.5.0
  at_cli_commons: ^1.1.0
  args:
    git:
      ref: gkc/show-aliases-in-usage
      url: https://github.com/gkc/args
  socket_connector: ^2.2.0
  dartssh2:
    git:
      url: https://github.com/atsign-foundation/dartssh2
      ref: trunk
  at_utils: 3.0.16
  logging: ^1.2.0
  chalkdart: ^2.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  mocktail: ^1.0.3
  build_runner: ^2.4.9
  build_version: ^2.1.1
