name: sshnp_webserver_demo
description: A new Flutter project
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  at_app_flutter: ^5.0.1
  at_client_mobile: ^3.2.6
  at_onboarding_flutter: ^6.1.0
  at_utils: ^3.0.11
  biometric_storage: ^5.0.0
  dartssh2: ^2.8.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http2: ^2.2.0
  noports_core:
    path: ../../../packages/noports_core
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ../.env
