version: "3.0"
services:
  sshnpd:
    image: sshnpd_webserver:local
    volumes:
      - ${HOME}/.atsign/keys:/atsign/.atsign/keys
      - type: bind # binded mount for demo purposes
        source: ./server/mount/var/www/html
        target: /var/www/html
      - type: bind # binded mount for demo purposes
        source: ./server/mount/var/www/html/api
        target: /var/www/html/api
    command: -a "${TO}" -m "${FROM}" -d "${DEVICE}" -s -u -v
