name: end2end_tests

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  SSHNP_ATSIGN: "@8incanteater"
  SSHNPD_ATSIGN: "@8052simple"
  SSHRVD_ATSIGN: "@8485wealthy51"
  DEVICE_NAME: "e2e"
  CONTAINER_TIMEOUT: 60 # 1 minute, exit if container takes longer than this to finish

jobs:
  end2end_tests_prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8485WEALTHY51 }}" > sshrvd/keys/${{ env.SSHRVD_ATSIGN }}_key.atKeys

      - name: Ensure keys are in place
        continue-on-error: true # in case step fails, pass anyway
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          ls sshnp/keys
          ls sshnpd/keys
          ls sshrvd/keys

      - name: Set up entrypoints
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE_NAME }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE_NAME }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}
          ./setup-sshrvd-entrypoint.sh ${{ env.SSHRVD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh
          cat sshrvd/entrypoint.sh

  end2end_tests_local-local-local:
    needs: [ end2end_tests_prep ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: build - docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
        run: |
          docker compose build

      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
        run: |
          docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}

      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
        run: |
          docker ps -a --no-trunc
          docker compose logs --timestamps

      - name: tear down - docker compose down
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
        run: |
          docker compose down

  end2end_tests_local-local-release:
    needs: [ end2end_tests_prep ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: build - docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker compose build

      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}

      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker ps -a --no-trunc
          docker compose logs --timestamps

      - name: tear down - docker compose down
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker compose down

  end2end_tests_local-trunk-release:
    needs: [ end2end_tests_prep ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: build - docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          docker compose build

      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}

      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          docker ps -a --no-trunc
          docker compose logs --timestamps

      - name: tear down - docker compose down
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          docker compose down
end2end_tests_trunk-local-release:
    needs: [ end2end_tests_prep ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: build - docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose build
      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker ps -a --no-trunc
          docker compose logs --timestamps
      - name: tear down - docker compose down
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose down

end2end_tests_release-release-release:
  needs: [ end2end_tests_prep ]
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: build - docker compose build
      working-directory: packages/sshnoports/test/end2end_tests/tests/release-release-release
      run: |
        docker compose build
    - name: run test - docker compose up
      working-directory: packages/sshnoports/test/end2end_tests/tests/release-release-release
      run: |
        docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
    - name: print logs
      working-directory: packages/sshnoports/test/end2end_tests/tests/release-release-release
      run: |
        docker ps -a --no-trunc
        docker compose logs --timestamps
    - name: tear down - docker compose down
      working-directory: packages/sshnoports/test/end2end_tests/tests/release-release-release
      run: |
        docker compose down

  end2end_tests_trunk-local-release:
    needs: [ end2end_tests_prep ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: build - docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose build
      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker ps -a --no-trunc
          docker compose logs --timestamps
      - name: tear down - docker compose down
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose down

  end2end_tests_trunk-trunk-release:
    needs: [ end2end_tests_prep ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: build - docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-release
        run: |
          docker compose build
      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-release
        run: |
          docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-release
        run: |
          docker ps -a --no-trunc
          docker compose logs --timestamps
      - name: tear down - docker compose down
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-release
        run: |
          docker compose down


  end2end_tests_trunk-trunk-trunk:
    needs: [ end2end_tests_prep ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: build - docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
        run: |
          docker compose build

      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
        run: |
          docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}

      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
        run: |
          docker ps -a --no-trunc
          docker compose logs --timestamps

      - name: tear down - docker compose down
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
        run: |
          docker compose down
