name: end2end_tests

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  SSHNP_ATSIGN: "@8incanteater"
  SSHNPD_ATSIGN: "@8052simple"
  SSHRVD_ATSIGN: "@8485wealthy51"
  DEVICE_NAME: "e2e"
  DOCKER_COMPOSE_UP_CMD: "docker compose up --exit-code-from=container-sshnp --attach=container-sshnp -t=60"
  DOCKER_COMPOSE_DOWN_CMD: "docker compose down"

jobs:
  end2end_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8485WEALTHY51 }}" > sshrvd/keys/${{ env.SSHRVD_ATSIGN }}_key.atKeys

      - name: Ensure keys are in place
        continue-on-error: true # in case step fails, pass anyway
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          ls sshnp/keys
          ls sshnpd/keys
          ls sshrvd/keys

      - name: Set up entrypoints
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE_NAME }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE_NAME }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}
          ./setup-sshrvd-entrypoint.sh ${{ env.SSHRVD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh
          cat sshrvd/entrypoint.sh

      - name: Docker compose build
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          docker compose build --no-cache

      - name: local-local-local
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}
          ${{ env.DOCKER_COMPOSE_DOWN_CMD }}

      - name: local-local-release
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}
          ${{ env.DOCKER_COMPOSE_DOWN_CMD }}

      - name: local-trunk-release
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}
          ${{ env.DOCKER_COMPOSE_DOWN_CMD }}

      - name: release-release-release
        working-directory: packages/sshnoports/test/end2end_tests/tests/release-release-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}
          ${{ env.DOCKER_COMPOSE_DOWN_CMD }}

      - name: trunk-local-release
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}
          ${{ env.DOCKER_COMPOSE_DOWN_CMD }}

      - name: trunk-trunk-release
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}
          ${{ env.DOCKER_COMPOSE_DOWN_CMD }}

      - name: trunk-trunk-trunk
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}
          ${{ env.DOCKER_COMPOSE_DOWN_CMD }}
