name: end2end_tests

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  SSHNP_ATSIGN: "@8incanteater"
  SSHNPD_ATSIGN: "@8052simple"
  SSHRVD_ATSIGN: "@8485wealthy51"
  DEVICE_NAME: "e2e"
  CONTAINER_TIMEOUT: 60 # 1 minute, exit if container takes longer than this to finish

jobs:
  e2e_prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8485WEALTHY51 }}" > sshrvd/keys/${{ env.SSHRVD_ATSIGN }}_key.atKeys

      - name: Ensure keys are in place
        continue-on-error: true # in case step fails, pass anyway
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          ls sshnp/keys
          ls sshnpd/keys
          ls sshrvd/keys

      - name: Set up entrypoints
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE_NAME }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE_NAME }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}
          ./setup-sshrvd-entrypoint.sh ${{ env.SSHRVD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh
          cat sshrvd/entrypoint.sh

      - name: Build all images
        working-directory: packages/sshnoports/test/end2end_tests/tests
        run: |
          cd local-trunk-release ; docker compose build ; cd ..

  e2e_local-local-local:
    runs-on: ubuntu-latest
    needs: e2e_prep
    steps:
      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
        run: |
          docker compose up --build --no-recreate --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
        run: |
          echo "Printing information ------"
          docker ps -a --no-trunc
          docker compose logs --timestamps
          docker compose down

  e2e_trunk-trunk-trunk:
    runs-on: ubuntu-latest
    needs: e2e_prep
    steps:
      - name: run test - docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
        run: |
          docker compose up --build --no-recreate --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      - name: print logs
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
        run: |
          echo "Printing information ------"
          docker ps -a --no-trunc
          docker compose logs --timestamps
          docker compose down
  e2e_trunk-local-release:

      # - name: trunk-trunk-trunk
      #   working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-trunk-trunk
      #   run: |
      #     docker compose up --build --no-recreate --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      #     echo "Printing information ------"
      #     docker ps -a --no-trunc
      #     docker compose logs --timestamps
      #     docker compose down

      # - name: trunk-local-release
      #   working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
      #   run: |
      #     docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      #     echo "Printing information ------"
      #     docker ps -a --no-trunc
      #     docker compose logs --timestamps
      #     docker compose down

      # - name: local-trunk-release
      #   working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
      #   run: |
      #     docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      #     docker ps -a --no-trunc
      #     docker compose logs --timestamps
      #     docker compose down

      # - name: local-local-local
      #   working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-local
      #   run: |
      #     docker compose up --exit-code-from=container-sshnp -t=${{ env.CONTAINER_TIMEOUT }}
      #     echo "Printing information ------"
      #     docker ps -a --no-trunc
      #     docker compose logs --timestamps
      #     docker compose down