name: end2end_tests

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  SSHNP_ATSIGN: "@8incanteater"
  SSHNPD_ATSIGN: "@8052simple"
  SSHRVD_ATSIGN: "@8485wealthy51"
  DOCKER_COMPOSE_UP_CMD: "docker compose up --build --exit-code-from=container-sshnp --quiet-pull -t=60 --no-recreate"
  DEVICE-NAME-LOCAL-LOCAL: "e2e1"
  DEVICE-NAME-LOCAL-RELEASE: "e2e2"
  DEVICE-NAME-LOCAL-TRUNK: "e2e3"
  DEVICE-NAME-RELEASE-LOCAL: "e2e4"
  DEVICE-NAME-TRUNK-LOCAL: "e2e5"

jobs:
  e2e-set-up-sshrvd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8485WEALTHY51 }}" > sshrvd/keys/${{ env.SSHRVD_ATSIGN }}_key.atKeys

      - name: Set up sshrvd
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshrvd-entrypoint.sh ${{ env.SSHRVD_ATSIGN }}

      - name: Ensure entrypoint exists
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshrvd/entrypoint.sh

      - name: Docker compose up
        working-directory: packages/sshnoports/test/end2end_tests/tests/sshrvd
        run: |
          docker compose up --build --quiet-pull --exit-code-from=container-sshrvd

  e2e-local-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up entrypoints
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE-NAME_LOCAL-LOCAL }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE-NAME_LOCAL-LOCAL }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker compose down


  e2e-local-trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE-NAME-LOCAL-TRUNK }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE-NAME-LOCAL-TRUNK }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk-release
        run: |
          docker compose down

  e2e-trunk-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE-NAME-TRUNK-LOCAL }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE-NAME-TRUNK-LOCAL }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local-release
        run: |
          docker compose down

  e2e-local-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE_NAME-LOCAL-RELEASE }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE_NAME-LOCAL-RELEASE }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release-release
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release-release
        run: |
          docker compose down

  e2e-release-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ env.DEVICE_NAME-RELEASE-LOCAL }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ env.DEVICE_NAME-RELEASE-LOCAL }} ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local-release
        run: |
          docker compose down