name: end2end_tests

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  SSHNP_ATSIGN: "@8incanteater"
  SSHNPD_ATSIGN: "@8052simple"
  # SSHRVD_ATSIGN: "@8485wealthy51"
  SSHRVD_ATSIGN: "@rv_am"
  DOCKER_COMPOSE_UP_CMD: "docker compose up --build --exit-code-from=container-sshnp --quiet-pull"
jobs:
  # e2e-set-up-sshrvd:
  #   concurrency: e2e-set-up-sshrvd
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

  #     - name: Copy keys
  #       working-directory: packages/sshnoports/test/end2end_tests/contexts
  #       run: |
  #         echo "${{ secrets.ATKEYS_8485WEALTHY51 }}" > sshrvd/keys/${{ env.SSHRVD_ATSIGN }}_key.atKeys

  #     - name: Set up sshrvd
  #       working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
  #       run: |
  #         ./setup-sshrvd-entrypoint.sh ${{ env.SSHRVD_ATSIGN }}

  #     - name: Ensure entrypoint exists
  #       working-directory: packages/sshnoports/test/end2end_tests/contexts
  #       run: |
  #         cat sshrvd/entrypoint.sh

  #     - name: Docker compose up
  #       working-directory: packages/sshnoports/test/end2end_tests/utility/sshrvd-release
  #       run: |
  #         docker compose up --build -d

  e2e-local-local:
    # needs: [e2e-set-up-sshrvd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up entrypoints
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}1 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}1 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-local
        run: |
          docker compose down

  e2e-local-trunk:
    # needs: [e2e-set-up-sshrvd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}2 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}2 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-trunk
        run: |
          docker compose down

  e2e-trunk-local:
    # needs: [e2e-set-up-sshrvd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}3 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}3 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/trunk-local
        run: |
          docker compose down

  e2e-local-release:
    # needs: [e2e-set-up-sshrvd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}4 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}4 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release
        run: |
          docker compose down

  e2e-release-local:
    # needs: [e2e-set-up-sshrvd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}5 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}5 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/release-local
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release-local
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release-local
        run: |
          docker compose down

  e2e-local-release3-2-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}6 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}6 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.2.0
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.2.0
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.2.0
        run: |
          docker compose down

  e2e-release3-2-0-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}7 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}7 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.2.0-local
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.2.0-local
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.2.0-local
        run: |
          docker compose down

  e2e-local-release3-3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}8 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}8 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.3.0
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.3.0
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.3.0
        run: |
          docker compose down

  e2e-release3-3-0-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}9 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}9 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

      - name: Ensure entrypoints exist
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.3.0-local
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.3.0-local
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.3.0-local
        run: |
          docker compose down

  e2e-release3-1-2-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}9 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}9 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

          - name: Ensure entrypoints exist
          working-directory: packages/sshnoports/test/end2end_tests/contexts
          run: |
            cat sshnp/entrypoint.sh
            cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.1.2-local
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.1.2-local
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/release3.1.2-local
        run: |
          docker compose down

  e2e-local-release3-1-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Copy keys
        working-directory: packages/sshnoports/test/end2end_tests/contexts
        run: |
          echo "${{ secrets.ATKEYS_8INCANTEATER }}" > sshnp/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets.ATKEYS_8052SIMPLE }}" > sshnpd/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Set up
        working-directory: packages/sshnoports/test/end2end_tests/tools/configuration
        run: |
          ./setup-sshnp-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}9 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }} ${{ env.SSHRVD_ATSIGN }}
          ./setup-sshnpd-entrypoint.sh ${{ github.run_id }}${{ github.run_attempt }}9 ${{ env.SSHNP_ATSIGN }} ${{ env.SSHNPD_ATSIGN }}

          - name: Ensure entrypoints exist
          working-directory: packages/sshnoports/test/end2end_tests/contexts
          run: |
            cat sshnp/entrypoint.sh
            cat sshnpd/entrypoint.sh

      - name: Test
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.1.2
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.1.2
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        if: always()
        working-directory: packages/sshnoports/test/end2end_tests/tests/local-release3.1.2
        run: |
          docker compose down