name: end2end_tests

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - trunk

env:
  SSHNP_ATSIGN: "@8incanteater"
  SSHNPD_ATSIGN: "@8052simple"
  SSHRVD_ATSIGN: "@8485wealthy51"

  PROD_RVD_ATSIGN: "@rv_am"
  DOCKER_COMPOSE_UP_CMD: "docker compose up --abort-on-container-exit"

  RELEASES: |
    latest
    v3.1.2
    v3.2.0
    v3.3.0
    v3.4.0

  BRANCHES: |
    trunk

jobs:
  e2e_test:
    # Don't run on PRs from a fork or Dependabot as the secrets aren't available
    if: ${{ github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        np: [local, trunk, installer]
        npd: [local, trunk]
        exclude:
          # Don't run these against themselves, they're irrelevant
          - np: trunk
            npd: trunk
        include:
          ### RVD TESTS ###
          # - np: local
          #   npd: local
          #   rvd: local
          #   rvd_atsign: "@8485wealthy51"

          - np: latest
            npd: latest
            rvd: local
            rvd_atsign: SSHRVD_ATSIGN
          ### SSHNPD INSTALLER TESTS ###
          - np: local
            npd: installer
            wait: 120

          - np: trunk
            npd: installer
            wait: 120

          - np: installer
            npd: installer
            wait: 120

          ### BACKWARD TESTS WITHOUT SYNC ###
          - np: local
            npd: latest
          - np: latest
            npd: local

          - np: local
            npd: v3.4.0
          - np: v3.4.0
            npd: local

          - np: local
            npd: v3.3.0
          - np: v3.3.0
            npd: local

          ### BACKWARD TESTS WITH SYNC ###
          - np: local
            npd: v3.2.0
            wait: 200
          - np: v3.2.0
            npd: local
    steps:
      - name: Show Matrix Values
        run: |
          echo "job index: ${{ strategy.job-index }}"
          echo "np: ${{ matrix.np }}"
          echo "npd: ${{ matrix.npd }}"
          echo "rvd: ${{ matrix.rvd }}"
          echo "rvd_atsign: ${{ env[matrix.rvd_atsign] || env.PROD_RVD_ATSIGN }}"
          echo "wait: ${{ matrix.wait }}"

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Uppercase sshnp atSign
        id: upper-sshnp
        uses: ASzc/change-string-case-action@58a73efb94b4f743e29a1b7f86794f4adb096410 #v5
        with:
          string: ${{ env.SSHNP_ATSIGN }}

      - name: Uppercase sshnpd atSign
        id: upper-sshnpd
        uses: ASzc/change-string-case-action@58a73efb94b4f743e29a1b7f86794f4adb096410 #v5
        with:
          string: ${{ env.SSHNPD_ATSIGN }}

      - name: Uppercase sshrvd atSign
        id: upper-sshrvd
        uses: ASzc/change-string-case-action@58a73efb94b4f743e29a1b7f86794f4adb096410 #v5
        with:
          string: ${{ env[matrix.rvd_atsign] || env.PROD_RVD_ATSIGN }}

      - name: Norm all atSigns for secrets
        run: |
          NORMED_SSHNP_ATSIGN=${{ steps.upper-sshnp.outputs.uppercase }}
          echo "NORMED_SSHNP_ATSIGN=${NORMED_SSHNP_ATSIGN:1}" >> $GITHUB_ENV
          NORMED_SSHNPD_ATSIGN=${{ steps.upper-sshnpd.outputs.uppercase }}
          echo "NORMED_SSHNPD_ATSIGN=${NORMED_SSHNPD_ATSIGN:1}" >> $GITHUB_ENV
          NORMED_SSHRVD_ATSIGN=${{ steps.upper-sshrvd.outputs.uppercase }}
          echo "NORMED_SSHRVD_ATSIGN=${NORMED_SSHRVD_ATSIGN:1}" >> $GITHUB_ENV

      - name: Copy NP/NPD keys
        working-directory: tests/end2end_tests/contexts
        run: |
          echo "${{ secrets[format('ATKEYS_{0}', env.NORMED_SSHNP_ATSIGN)] }}" > sshnp/.atsign/keys/${{ env.SSHNP_ATSIGN }}_key.atKeys
          echo "${{ secrets[format('ATKEYS_{0}', env.NORMED_SSHNPD_ATSIGN)] }}" > sshnpd/.atsign/keys/${{ env.SSHNPD_ATSIGN }}_key.atKeys

      - name: Copy RVD keys
        working-directory: tests/end2end_tests/contexts
        if: matrix.rvd
        run: |
          echo "${{ secrets[format('ATKEYS_{0}', env.NORMED_SSHRVD_ATSIGN)] }}" > sshrvd/.atsign/keys/${{ env[matrix.rvd_atsign] }}_key.atKeys

      - name: Set up entrypoints
        uses: ./.github/composite/setup_entrypoints
        with:
          sshnp: ${{ matrix.np }}
          sshnp_atsign: ${{ env.SSHNP_ATSIGN }}
          sshnpd: ${{ matrix.npd }}
          sshnpd_atsign: ${{ env.SSHNPD_ATSIGN }}
          sshrvd_atsign: ${{ env[matrix.rvd_atsign] || env.PROD_RVD_ATSIGN }}
          devicename: ${{ github.run_id }}${{ github.run_attempt }}${{ strategy.job-index }}
          wait_time: ${{ matrix.wait }}

      - name: Ensure entrypoints exist
        working-directory: tests/end2end_tests/contexts
        run: |
          cat sshnp/entrypoint.sh
          cat sshnpd/entrypoint.sh
          cat sshrvd/entrypoint.sh

      - name: Create docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        run: |
          cat docker-compose-base.yaml > docker-compose.yaml

      - name: Add runtime-release image to docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        if: ${{ contains(env.RELEASES, matrix.np) || contains(env.RELEASES, matrix.npd) || (matrix.rvd && contains(env.RELEASES, matrix.rvd)) }}
        run: |
          cat service-image-runtime-release.yaml >> docker-compose.yaml
          if [ "${{contains(env.RELEASES, matrix.np)}}" = true ]; then
            echo '        - release=${{ matrix.np }}' >> docker-compose.yaml
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.np }}' >> docker-compose.yaml
          elif [ "${{contains(env.RELEASES, matrix.npd)}}" = true ]; then
            echo '        - release=${{ matrix.npd }}' >> docker-compose.yaml
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.npd }}' >> docker-compose.yaml
          elif [ "${{contains(env.RELEASES, matrix.rvd)}}" = true ]; then
            echo '        - release=${{ matrix.rvd }}' >> docker-compose.yaml
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.rvd }}' >> docker-compose.yaml
          fi

      - name: Add runtime-branch image to docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        if: ${{ contains(env.BRANCHES, matrix.np) || contains(env.BRANCHES, matrix.npd) || (matrix.rvd && contains(env.BRANCHES, matrix.rvd)) }}
        run: |
          cat service-image-runtime-branch.yaml >> docker-compose.yaml
          if [ "${{contains(env.BRANCHES, matrix.np)}}" = true ]; then
            echo '        - branch=${{ matrix.np }}' >> docker-compose.yaml
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.np }}' >> docker-compose.yaml
          elif [ "${{contains(env.BRANCHES, matrix.npd)}}" = true ]; then
            echo '        - branch=${{ matrix.npd }}' >> docker-compose.yaml
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.npd }}' >> docker-compose.yaml
          elif [ "${{contains(env.BRANCHES, matrix.rvd)}}" = true ]; then
            echo '        - branch=${{ matrix.rvd }}' >> docker-compose.yaml
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.rvd }}' >> docker-compose.yaml
          fi

      - name: Add runtime-sshnp-installer image to docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        if: ${{ matrix.np == 'installer' }}
        run: |
          cat service-image-runtime-sshnp-installer.yaml >> docker-compose.yaml
          echo '        - client_atsign="${{ env.SSHNP_ATSIGN }}"' >> docker-compose.yaml
          echo '        - device_atsign="${{ env.SSHNPD_ATSIGN }}"' >> docker-compose.yaml
          echo '        - host_atsign="${{ env[matrix.rvd_atsign] || env.PROD_RVD_ATSIGN }}"' >> docker-compose.yaml
          echo '    image: atsigncompany/sshnp-e2e-runtime:sshnp-installer' >> docker-compose.yaml

      - name: Add runtime-sshnpd-installer image to docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        if: ${{ matrix.npd == 'installer' }}
        run: |
          cat service-image-runtime-sshnpd-installer.yaml >> docker-compose.yaml
          echo '        - client_atsign="${{ env.SSHNP_ATSIGN }}"' >> docker-compose.yaml
          echo '        - device_atsign="${{ env.SSHNPD_ATSIGN }}"' >> docker-compose.yaml
          echo '        - device_name=${{ github.run_id }}${{ github.run_attempt }}${{ strategy.job-index }}' >> docker-compose.yaml
          echo '    image: atsigncompany/sshnp-e2e-runtime:sshnpd-installer' >> docker-compose.yaml

      - name: Add container-sshnp to docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        run: |
          cat service-container-sshnp.yaml >> docker-compose.yaml
          if [ "${{ matrix.np }}" = 'installer' ]; then
            echo '    image: atsigncompany/sshnp-e2e-runtime:sshnp-installer' >> docker-compose.yaml
          else
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.np }}' >> docker-compose.yaml
          fi
          echo '    depends_on:' >> docker-compose.yaml
          echo '      container-sshnpd:' >> docker-compose.yaml
          echo '        condition: service_healthy' >> docker-compose.yaml
          if [ "${{contains(env.RELEASES, matrix.np)}}" = true ]; then
            echo '      image-runtime-release:' >> docker-compose.yaml
          elif [ "${{contains(env.BRANCHES, matrix.np)}}" = true ]; then
            echo '      image-runtime-branch:' >> docker-compose.yaml
          elif [ "${{ matrix.np }}" = 'installer' ]; then
            echo '      image-runtime-sshnp-installer:' >> docker-compose.yaml
          else
            echo '      image-runtime-local:' >> docker-compose.yaml
          fi
          echo '        condition: service_started' >> docker-compose.yaml

      - name: Add container-sshnpd to docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        run: |
          cat service-container-sshnpd.yaml >> docker-compose.yaml
          if [ "${{ matrix.npd }}" = 'installer' ]; then
            echo '    image: atsigncompany/sshnp-e2e-runtime:sshnpd-installer' >> docker-compose.yaml
          else
            echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.npd }}' >> docker-compose.yaml
          fi
          echo '    depends_on:' >> docker-compose.yaml
          if [ "${{ matrix.rvd }}" = true ]; then
            echo '      - container-sshrvd' >> docker-compose.yaml
          fi
          if [ "${{contains(env.RELEASES, matrix.npd)}}" = true ]; then
            echo '      - image-runtime-release' >> docker-compose.yaml
          elif [ "${{contains(env.BRANCHES, matrix.npd)}}" = true ]; then
            echo '      - image-runtime-branch' >> docker-compose.yaml
          elif [ "${{ matrix.npd }}" = 'installer' ]; then
            echo '      - image-runtime-sshnpd-installer' >> docker-compose.yaml
          else
            echo '      - image-runtime-local' >> docker-compose.yaml
          fi

      - name: Add container-sshrvd to docker-compose.yaml
        working-directory: tests/end2end_tests/tests
        if: matrix.rvd
        run: |
          cat service-container-sshrvd.yaml >> docker-compose.yaml
          echo '    image: atsigncompany/sshnp-e2e-runtime:${{ matrix.rvd }}' >> docker-compose.yaml
          echo '    depends_on:' >> docker-compose.yaml
          if [ "${{contains(env.RELEASES, matrix.rvd)}}" = true ]; then
            echo '      - image-runtime-release' >> docker-compose.yaml
          elif [ "${{contains(env.BRANCHES, matrix.rvd)}}" = true ]; then
            echo '      - image-runtime-branch' >> docker-compose.yaml
          else
            echo '      - image-runtime-local' >> docker-compose.yaml
          fi

      - name: docker-compose.yaml
        if: always()
        working-directory: tests/end2end_tests/tests
        run: |
          cat docker-compose.yaml

      - name: Build
        working-directory: tests/end2end_tests/tests
        run: |
          docker compose build

      - name: Test
        working-directory: tests/end2end_tests/tests
        run: |
          ${{ env.DOCKER_COMPOSE_UP_CMD }}

      - name: Logs
        if: always()
        working-directory: tests/end2end_tests/tests
        run: |
          docker compose ps -a
          docker compose logs --timestamps

      - name: Tear down
        # Always tear down outside of the act environment
        # but don't tear down on failure in the act environment
        if: ${{ !env.ACT }} || success()
        working-directory: tests/end2end_tests/tests
        run: |
          docker compose down
