name: Gitbook Review
on:
  push:
    branches:
     - gitbook

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Authenticate GitHub CLI
        run: |
         echo -e ${{ secrets.MY_GITHUB_TOKEN }} | gh auth login --with-token 

      - name: Create Pull Request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up \
            --base 'trunk' \
            --head 'gitbook' \
            --reviewer 'xavierchanth' \
            --fill;

