name: Gitbook Review
on:
  push:
    branches:
      - gitbook

permissions:
  contents: read

jobs:
  create-pull-request:
    env:
      branch: gitbook

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Authenticate GitHub CLI
        run: |
          echo -e ${{ secrets.MY_GITHUB_TOKEN }} | gh auth login --with-token 

      - name: Create Pull Request
        run: |
          gh pr create \
            --base 'trunk' \
            --head 'gitbook' \
            --reviewer 'xavierchanth' \
            --title 'docs(automated): Update docs from Gitbook' \
            --body 'Sync Gitbook docs branch to trunk' || \
          echo "Already created?";
