name: Python tests
on:
  pull_request:
    paths:
      - 'packages/python/**'

# Declare default permissions as read only.
permissions: read-all

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1.0.0
        with:
          src: './packages/python'
