name: noports_core
description: Core library code for sshnoports

# NOTE: If you update the version number here, you
# must also update it in version.dart
version: 4.0.0

homepage: https://docs.atsign.com/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  at_chops: ^1.0.4
  at_client: ^3.0.65
  at_utils: ^3.0.15
  cryptography: ^2.7.0
  dartssh2: ^2.8.2
  meta: ^1.9.1
  openssh_ed25519: ^1.1.0
  path: ^1.8.3
  posix: ^5.0.0
  socket_connector: ^1.0.11
  ssh_key: ^0.8.0
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.4
